export { renderTasks } from './renderTasks.js'
export { updateTime } from './clock.js'
export { setClickTaskButtons } from './setHandlers.js'
export { removeTask } from './removeTask.js'
export { updateCounters } from './updateCounters.js'
